### ISSUE TITLE
Suggest using local font instead of google font

### ISSUE THREAD

**Issue by hiberabyss** [sjaakvandenberg/cleaver-dark#1]
Since google is blocked in china, using  google font makes it really slow to load the page.

PS: Can you publish the source code of `http://svdb.co/cleaver-dark/` ?  I'm not very familiar with markdown, I think I can learn a lot from your source code.

Thank you very much !

**Comment by sjaakvandenberg** [comment]
Hmm, I didn't know that Google Fonts was part of the Great Firewall's block list. Do you know of any alternative CDNs that are accessible for you?

You can find the source code of `http://svdb.co/cleaver-dark/` on the `gh-pages` branch [here](https://github.com/sjaakvandenberg/cleaver-dark/tree/gh-pages). Here's a [Gist](https://gist.github.com/sjaakvandenberg/2592f41fd124ce85f018) (raw code [here](https://gist.github.com/sjaakvandenberg/2592f41fd124ce85f018/raw/baa8e053375e01a6dcbb9ea8bff530e70519c837/basic.md))with the source code for the presentation, with the YAML settings at the top. When run with Cleaver, it compiles into [this](https://github.com/sjaakvandenberg/cleaver-dark/blob/master/index.html). The [Markdown](https://daringfireball.net/projects/markdown/syntax) used is the same language you can use on Github for comments.

**Comment by hiberabyss** [comment]
Thanks for your reply! I found a google font CDN `fonts.useso.com` provided by a chinese company 360, after replace google font with it,  the page can be loaded quickly.

PS: I'm still curious whether there is an easy way to load the font from local, this makes it possible to compile the markdown file when offline.

**Comment by sjaakvandenberg** [comment]
I don't think I'm going to switch to that CDN just yet, as most of my visitors are non-Chinese are get better load times that way. I will consider hosting fonts on Github as well though. I'll have to do some tests to see how it will affect load times.

You can however just clone the repo and swap out the fonts yourself and load them locally. If you view the source of `https://github.com/sjaakvandenberg/cleaver-dark/blob/master/index.html`, you can swap out

``` html
<link href='http://fonts.googleapis.com/css?family=Source+Code+Pro:200,300,400,500,600,700,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

```

With a local font. If you follow the link `http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800`, you can save the fonts locally and load them that way. Or is that blocked for you also? You should be able to find these fonts elsewhere online.

**Comment by hiberabyss** [comment]
I have download the fonts,  I'll try to load them in local repo. Hosting fonts on github is a good idea. Thanks for your help very much!

**Comment by sjaakvandenberg** [comment]
No problem!

**Comment by sjaakvandenberg** [comment]
I've switched both [cleaver-dark](https://github.com/sjaakvandenberg/cleaver-dark) and [cleaver-light](https://github.com/sjaakvandenberg/cleaver-light) to use local fonts. Right now, they're using WOFF2 and WOFF fonts. You can generate these yourself from TTF files [here](http://www.fontsquirrel.com/tools/webfont-generator). Browser support is very good. See [Chris Coyier's article](https://css-tricks.com/snippets/css/using-font-face/) on it, and check out the [WOFF2](http://caniuse.com/#feat=woff2) and [WOFF](http://caniuse.com/#feat=woff) Caniuse pages.
